### PR TITLE
Fix should update cluster information to the remote store first

### LINKED ISSUE #221: suggest to enable retry migrating the same slot and target shard
https://github.com/apache/kvrocks-controller/blob/2649b8f08c1bbc851509a4f182970d3294216def/store/cluster.go#L203C1-L205C3

in controller/cluster.go, method tryUpdateMigrationStatus, it may not get migrating_state or migrating_slot data when executing 'cluster info' cmd on a master node, then switch will select the default case, then the migrating_slot and target_shard_index in cluster info can not be updated any more. this will stop any slot migrate.

suggest to enable retry migrating the same slot and target shard,
`	if cluster.Shards[sourceShardIdx].IsMigrating() || cluster.Shards[targetShardIdx].IsMigrating() {
		if !(cluster.Shards[sourceShardIdx].MigratingSlot == slot && cluster.Shards[sourceShardIdx].TargetShardIndex == targetShardIdx) {
			return consts.ErrShardSlotIsMigrating
		}
	}`

let the cluster node can exec the 'clusterx migrate' cmd again.

### PR DESCRIPTION
**Pull request by git-hulk**
Currently, the cluster migration will update the local cluster before the remote store, so it might cause the local cluster to stop checking the cluster migration even if it failed to set the remote store.

This closes #221.

### CODE REVIEW

File: store/cluster.go [hunk 1]
```diff
@@ -77,6 +77,18 @@ func NewCluster(name string, nodes []string, replicas int) (*Cluster, error) {
 	return cluster, nil
 }
 
+func (cluster *Cluster) Clone() *Cluster {
+	clone := &Cluster{
+		Name:   cluster.Name,
+		Shards: make([]*Shard, 0),
+	}
+	clone.Version.Store(cluster.Version.Load())
+	for _, shard := range cluster.Shards {
```
Comment (torwig) [inline store/cluster.go:86]: Is it possible that someone can modify `cluster.Shards` (it's a slice) while we are iterating over it?
I see this:
```
case <-ticker.C:
			c.clusterMu.Lock()
			cluster := c.cluster
			c.clusterMu.Unlock()
			if cluster == nil {
				continue
			}
			c.tryUpdateMigrationStatus(c.ctx, cluster.Clone())
```

But technically `cluster := c.cluster` doesn't make a deep copy. Maybe we need to call `cluster.Clone()` under the lock instead of assignment?

Comment (git-hulk) [reply store/cluster.go:86]: Good catch, it should be better to clone with the lock guard.

**Review by torwig — APPROVED** [review]

**Review by PragmaTwice — APPROVED** [review]
