### PR TITLE
Fix nil pointer when cloning the cluster

### LINKED ISSUE #239: Flaky test caused by the cluster clone
The cluster might be an empty state, so needs to check if it's nil before cloning: https://github.com/apache/kvrocks-controller/actions/runs/12475622172/job/34819307016#step:6:457

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #239

### CODE REVIEW

**Review by PragmaTwice — APPROVED** [review]

File: store/cluster.go [hunk 1]
```diff
@@ -78,6 +78,10 @@ func NewCluster(name string, nodes []string, replicas int) (*Cluster, error) {
 }
 
 func (cluster *Cluster) Clone() *Cluster {
+	if cluster == nil {
```
Comment (PragmaTwice) [inline store/cluster.go]: I prefer to check before any method call, e.g. `if c != nil { c.Clone() }`.

Comment (git-hulk) [reply store/cluster.go]: Yes, it will be better to keep consistent with other methods. Done.

**Review by PragmaTwice — APPROVED** [review]
