### PR TITLE
Fix nil pointer when print MigratingSlot string function

### LINKED ISSUE #331: Fix nil pointer when print MigratingSlot string function
migrate_slot is nil when finish slot range. if print migrateslot message cause nil pointer

### PR DESCRIPTION
**Pull request by hll1213181368**
This closes #331.

### CODE REVIEW

File: store/slot.go [hunk 1]
```diff
@@ -49,6 +49,13 @@ type MigratingSlot struct {
 	IsMigrating bool
 }
 
+func (migratingSlot *MigratingSlot) String() string {
+	if migratingSlot == nil {
+		return ""
+	}
+	return strconv.Itoa(migratingSlot.Start) + "-" + strconv.Itoa(migratingSlot.Stop)
+}
```
Comment (git-hulk) [inline store/slot.go]:
```suggestion
func (migratingSlot *MigratingSlot) String() string {
	if migratingSlot == nil {
		return ""
	}
	return migratingSlot.SlotRange.String()
}
```

**Review by git-hulk — APPROVED** [review]
