### PR TITLE
Fix possible slot range loss in the importing API

### LINKED ISSUE #184: slot range lost, there will be fields[9] slot range if a master did slot and data migration before
https://github.com/apache/kvrocks-controller/blob/3a336a9b88faaef3678f2cfcdf81f67ae23d9d14/store/cluster.go#L277

node string will like
xxxx ip:6666@xxx master - timestamp timestamp 117 connected 0-123 124-5460

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #184

Currently, the controller only parsed the first slot range
when importing the cluster. So it might be lost remain slot ranges
if the shard has more than one slot range.

### CODE REVIEW

File: store/cluster.go [hunk 1]
```diff
@@ -17,6 +17,7 @@
  * under the License.
  *
  */
+
```
Comment (git-hulk) [inline store/cluster.go:20]: Should add an empty line between package comments and the name

**Review by torwig — APPROVED** [review]
